### PR TITLE
Added daemon state machine.

### PR DESCRIPTION
**Pull request by erlstanleylee**
Added state-machine for daemon.

### CODE REVIEW

**Review by alexzma — CHANGES_REQUESTED** [review]
I think client cancel job should go from HasJob to Advertising instead of from Do Work to Advertising, since the client could cancel while the daemon is sending back data or troubleshooting. Then, the daemon should stop sending the data to the client concerning the job.

Also, could you label the transition between return output and advertising and the transition between clean up and server closed? I know they are pretty self-explanatory, but just in case.

**Comment by erlstanleylee** [comment]
@alexzma Made the requested changes.

**Review by alexzma — APPROVED** [review]
Looks good!

**Comment by rvighne** [comment]
UML State Machine diagram for Daemon

**Review by rvighne — APPROVED** [review]
Can you remove the final "Close Server" state (i.e.  make it go directly to the end state)? Other than that, LGTM.

Btw, the "Advertising" phase of isn't exactly how it works now, but this is still a fine diagram.

**Pull request merged**
