### PR TITLE
JobOrderer StateMachine

### PR DESCRIPTION
**Pull request by Rohanator9000**

### CODE REVIEW

**Comment by Rohanator9000** [comment]
Here's what it looks like right now: 
image

**Comment by rvighne** [comment]
This is pretty good, but you might want to model this more closely after the JobOrderer implementation. E.g. add state machine variables for "inProgress", "sources", etc. and have the "job reported completed/failed" transitions update those variables. You can also use it to detect "all jobs are done".

**Review by erlstanleylee — APPROVED** [review]
This looks good.

**Comment by Rohanator9000** [comment]
> This is pretty good, but you might want to model this more closely after the JobOrderer implementation. E.g. add state machine variables for "inProgress", "sources", etc. and have the "job reported completed/failed" transitions update those variables. You can also use it to detect "all jobs are done".

I added `sources`, `nonSources`, and `inProgress`. I omitted `jobToDependents` and `jobToNumCompletedPrereqs` because we're low on space. Regardless, the diagram is pretty wide now 😅:

JobOrdererStateMachine

**Review by rvighne — APPROVED** [review]
😂 yeah it might help to put some line breaks in there, but content-wise this is good.

**Comment by Rohanator9000** [comment]
> 😂 yeah it might help to put some line breaks in there, but content-wise this is good.

@rvighne Added line breaks. New diagram:

image

**Review by rvighne — APPROVED** [review]

**Pull request merged**
