### PR TITLE
sequence diagram(sequence1.plantuml)

### PR DESCRIPTION
**Pull request by erlstanleylee**
Added my sequence diagram focusing on the communication that client does with joborderer and daemon.

### CODE REVIEW

**Review by yashlala — CHANGES_REQUESTED** [review]
This seems to indicate that the user talks directly to the client instead of going through the controller. Sending the user request through the controller first would be consistent with the rest of the documentation.

**Comment by erlstanleylee** [comment]
@yashlala I added the controller and parser entity.

**Comment by rvighne** [comment]
# Failure Sequence
UML Sequence Diagram for Failure

# Success Sequence
UML Sequence diagram for Success

**Review by yashlala — APPROVED** [review]

**Review by rvighne — APPROVED** [review]
Looks good.

**Pull request merged**
