### PR TITLE
Activity diagram

### PR DESCRIPTION
**Pull request by alexzma**
Started the activity diagram. Has overall interactions between controller, client, and daemon.

### CODE REVIEW

**Comment by rvighne** [comment]
UML Activity diagram

**Review by rvighne — CHANGES_REQUESTED** [review]
This is solid diagram, nice work.

Can we show the parallelism in the client somehow? Since activity diagram has the fork/join thing, we can show daemons being discovered in parallel with work being done. The join would happen once all jobs are done. (I probably haven't described that exactly how it maps to UML, but this general idea).

**Comment by alexzma** [comment]
Activity-Diagram
New version of overall activity diagram.

**Review by rvighne — APPROVED** [review]
This is some top-tier UML craftsmanship here

**Review by yashlala — APPROVED** [review]

**Pull request merged**
