### PR TITLE
Class diagram.

### PR DESCRIPTION
**Pull request by alexzma**
This is the class diagram.

### CODE REVIEW

**Comment by rvighne** [comment]
Rendering of the diagram: Junknet UML class diagram preview

In the future, let's always attach this link to the PR so others can easily see the diagram.

**Review by rvighne — APPROVED** [review]
Overall looks good. I would recommend
- adding multiplicity to all of the "aggregation arrows" (the ones with hollow diamond)
- make the Docker-related functions private, and remove some of them and simplify the signatures (that box takes up way too much of the diagram and we might not be able to paste this into a google doc at that size)

**Comment by alexzma** [comment]
ClassDiagram
Updated class diagram

**Comment by rvighne** [comment]
Forgot to mention this before: client to daemon multiplicity should be many-to-many.

Also, the Daemon function signatures are still not really a manageable size. We don't have to be completely accurate with the types there, maybe just `attachStreams(in stdin, out stdout, out stderr)`?

And we can remove `in` from all parameters, since that's the default. Any other space saving ideas?

**Comment by yashlala** [comment]
The Parser code is currently in a class; however, it's entirely static (might as well just put it in a module). 
I'm not sure how this code would fit into a class diagram, as the Controller wouldn't technically contain any Parser objects. Any objection to my adding the below code to the diagram? 

```
class Parser{
+ parseMakefile(in file: string): Job [*]
}
Controller "1" --* "1" Parser
```

**Comment by alexzma** [comment]
> The Parser code is currently in a class; however, it's entirely static (might as well just put it in a module).
> I'm not sure how this code would fit into a class diagram, as the Controller wouldn't technically contain any Parser objects. I think it might be safer to add it to the diagram anyways -- any objections to my adding something the below snippet?
> 
> ```
> class Parser{
> + parseMakefile(in file: string): Job [*]
> }
> Controller "1" --* "1" Parser
> ```

No objections

**Comment by yashlala** [comment]
Alright. Added it to the PR, with some minor tweaks (composition arrow was in the wrong direction). 

Diagram shown below. 

image

**Review by yashlala — APPROVED** [review]

**Pull request merged**
